---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

mas_installed_apps:
  - { id: 443987910, name: "1Password" }
  - { id: 497799835, name: "Xcode" }
  - { id: 937984704, name: "Amphetamine"}
  - { id: 425424353, name: "The Unarchiver"}
  - { id: 441258766, name: "Magnet"}
  - { id: 1540160809, name: "OneTab"}
  - { id: 1622835804, name: "Kagi for Safari"}
  - { id: 931571202, name: "QuickShade"}

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Apps
- Mail
- Maps
- Photos
- FaceTime
- Phone
- Calendar
- Contacts
- Reminders
- TV
- Games
- iPhone Mirroring
- Launchpad
- Podcasts
dockitems_persist:
- name: "Sublime Text"
  path: "/Applications/Sublime Text.app/"
  pos: 5
- name: "Fantastical"
  path: "/Applications/Fantastical.app/"
  pos: 6
- name: "Signal"
  path: "/Applications/Signal.app/"
- name: "Firefox"
  path: "/Applications/Firefox.app/"
- name: "iTerm"
  path: "/Applications/iTerm.app/"

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  na28046 ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/nati0n/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/code/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - nvm
  - php
  - pngpaste
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - alfred
  - vivaldi
  - docker
  - signal
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - 1password
  - anki
  - appcleaner
  - bartender
  - cool-retro-term
  - cyberduck
  - discord
  - iterm2
  - ghostty
  - kitty
  - orion
  - transmission
  - transmit
  - vmware-fusion
  - wireshark
  - vlc
  - visual-studio-code
  - typora
  - keka
  - soundsource
  - scroll-reverser
  - insta360-link-controller
  - adobe-acrobat-reader
  - mimestream

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
